on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: Python FE

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.11'
        coverage:
          - '6.0'
    name: Python ${{ matrix.python }} on coverage ${{ matrix.coverage }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install coverage==${{ matrix.coverage}} && pip install . && pip install -r requirements-dev.txt
      - name: Run tests
        run: python -m pytest
