# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    paths: 
      - features/**
  pull_request:
    branches: [ "main" ]
    paths:
      - feautres/**

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    - name: Test with pytest
      run: |
        pytest unit-tests/testdatetransformation.py --doctest-modules --junitxml=junit/test-results.xml --cov=features --cov-report=xml --cov-report=html
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml
        
    - name: update file and push to remote
      run: |
        echo "Test push commit to the remote in the workflow" >> test.txt
        git config --global user.name "rchan-cup"
        git config --global user.email "rose.chan@cambridge.org"

        git add -A
        git commit -m "Update test.txt"
        git push
